### ISSUE TITLE
Ability to add widgets for different locations.

### ISSUE THREAD

**Issue by MillionsToOne** [breezy-weather/breezy-weather#642] opened 2024-01-26 11:18 UTC
### Describe your idea

Currently, there's no way to choose the location of your home screen widgets. Adding the ability to choose the weather of the location you choose, instead of the one selected to show first inside the app, would greatly enhance user experience.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [x] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2024-01-26 12:12
Duplicate of #391

**Closed by papjul** 2024-01-26 12:12 UTC
Labels: Idea, Needs review, Widgets
