### ISSUE TITLE
Location changes back to first location when saving updated weather data main source

### ISSUE THREAD

**Issue by cskwrd** [breezy-weather/breezy-weather#540] opened 2023-10-23 12:57 UTC
### Steps to reproduce

1. Download app from F-Droid.
2. Deny location permission.
3. Add 2 or more locations using location search.
4. Select a location (that isn't the first in the list) from the Locations screen.
5. Scroll to the bottom, and update the weather source. (I flip flopped between Open-Meteo and AccuWeather.)
6. Save change
7. Notice the location has changed from the selected location to the location appearing first on the Locations screen.

### Expected behavior

The currently viewed location should stay the same. (Maybe even scroll position.)

### Actual behavior

The user is taken to the location appearing first on the Locations screen.

### Weather source used

Switched between Open-Meteo and AccuWeather 

### Breezy Weather version

4.6.9-beta

### Android version

GrapheneOS - Android 14

### Device

Pixel 5a 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.9 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2023-10-23 13:42
Duplicate of #365

**Closed by papjul** 2023-10-23 13:42 UTC
Labels: Bug, Needs review
