### ISSUE TITLE
Option to show "Feels like" temperature on Material You Current widget

### ISSUE THREAD

**Issue by lokesh-krishna** [breezy-weather/breezy-weather#849] opened 2024-03-26 04:54 UTC
### Describe your idea

The Material You Current widget is beautiful and my favourite widget on my phone.

Could we please have a toggle or option to display the current "feels like" temperature instead of the current temperature?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 5.1.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2024-03-26 05:54
Duplicate of #446

**Closed by papjul** 2024-03-26 05:54 UTC
Labels: Idea, Needs review
