### ISSUE TITLE
UI header improvement

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [breezy-weather/breezy-weather#491] opened 2023-09-28 20:12 UTC
### Describe your idea

Just installed the app so i wasn't familiar with the settings menu. I didn't know in what submenu i was because the header still says Settings when u are in the submenu.

https://github.com/breezy-weather/breezy-weather/assets/73130443/559de69b-a904-4da5-bee7-0c52989c00b9

IMO settings header title should be replaced with the title of the submenu

https://github.com/breezy-weather/breezy-weather/assets/73130443/650312bf-fce3-4c5b-bf03-594fd6963681

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2023-09-28 20:37
Duplicate of #99

**Closed by papjul** 2023-09-28 20:37 UTC
Labels: Idea, Needs review
