### ISSUE TITLE
Hide location list by default

### ISSUE THREAD

**Issue by lmas** [breezy-weather/breezy-weather#1303] opened 2024-09-15 07:21 UTC
### Steps to reproduce

Open app, the location list is visible.
![test](https://github.com/user-attachments/assets/e0dd7a48-c0aa-4850-8ff8-a18b8a32b12a)

### Expected behavior

Open app, the location list is hidden.
![test1](https://github.com/user-attachments/assets/346a0fcc-6f56-479e-8be3-df332757f916)

### Actual behavior

Could add a settings toggle for controlling if the location list should be hidden or visible at startup?

### Weather source used

openmeteo or whatev

### Breezy Weather version

5.2.7_freenet

### Android version

Android 13

### Device

Samsung Galaxy Tab

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2024-09-15 07:44
Duplicate of #745

**Closed by papjul** 2024-09-15 07:44 UTC
Labels: Bug, Needs review
