### ISSUE TITLE
More compact main screen for 16:9 devices

### ISSUE THREAD

**Issue by ludles** [breezy-weather/breezy-weather#679] opened 2024-02-16 19:01 UTC
### Steps to reproduce

The main screen is too sparse to see any chart. The old Geometric Weather layout is preferable.

### Expected behavior

The shown example in README:
![example](https://github.com/breezy-weather/breezy-weather/raw/main/fastlane/metadata/android/en-US/images/phoneScreenshots/01.png)

or the old Geometric Weather layout:
![Snipaste_2024-02-16_13-19-14](https://github.com/breezy-weather/breezy-weather/assets/37469405/58cb978f-664d-4e59-ab55-bba9578b8c2e)

or something like after removing some detail entries, and setting this app's DPI to 350 and font scaling to 110%, and scrolling up a bit:
![Snipaste_2024-02-16_13-43-44](https://github.com/breezy-weather/breezy-weather/assets/37469405/7aa89497-32d7-4c5f-92cd-9bc3e439db56)
(This also affects the widget, so it's not a solution.)

### Actual behavior

How it currently looks:

![Snipaste_2024-02-16_13-20-08](https://github.com/breezy-weather/breezy-weather/assets/37469405/f832118a-4b93-471f-9399-364f8e06c1c3)

### Weather source used

AccuWeather

### Breezy Weather version

v4.6.14-beta

### Android version

Android 9

### Device

xiaomi-sagit

### Other details

My screen specs for reproducing propose:

![Snipaste_2024-02-16_14-09-00](https://github.com/breezy-weather/breezy-weather/assets/37469405/183bc708-8c1c-40ae-9ba2-a032bd320d5b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2024-02-16 19:52
I'm not sure what to answer, it looks like you figured out your own solution? Either you change Android display size (screenshot 1), use Geometric Weather (screenshot 2) or remove details (screenshot 3)?

In my opinion, option 3 is the best if you're interested in seeing chart more than current details, as this is basically the same as option 2 but option 2 has more spacing on top, and option 1 would apply system-wide which is probably not what you want.

Note that in screenshot 3, you scrolled down. If the implied suggestion is to remove that spacing, it's not going to happen as that would overlap a background-less text on top of a drawing (white clouds or whatever is the current weather condition). That drawing fades out when you scroll down, so it doesn't cause contrast issues in the current state.

**Comment by ludles** [comment] 2024-02-16 20:15
> I'm not sure what to answer, it looks like you figured out your own solution? Either you change Android display size (screenshot 1), use Geometric Weather (screenshot 2) or remove details (screenshot 3)?

- Screenshot 1 is the one on the README page, which I did not manage to achieve.
- Screenshot 3 includes 
  1. removing some detail entries (losing information);
  2. setting this app's DPI to 350 and font scaling to 110% (**root required**);
  3. scrolling up a bit (manually, every time);
  - And this tweak of display settings also affects the widget, so it's not really a solution.

> In my opinion, option 3 is the best if you're interested in seeing chart more than current details, as this is basically the same as option 2 but option 2 has more spacing on top, and option 1 would apply system-wide which is probably not what you want.
> 
> Note that in screenshot 3, you scrolled down. If the implied suggestion is to remove that spacing, it's not going to happen as that would overlap a background-less text on top of a drawing (white clouds or whatever is the current weather condition). That drawing fades out when you scroll down, so it doesn't cause contrast issues in the current state.

I would expect to see Screenshot 4 to be similar to Screenshot 1. Currently, there is too much top spacing in Screenshot 4 compared with Screenshot 1. And the font size of temperature and the spacing between detail entries can also be improved.

But IMHO, the old Geometric Weather (Screenshot 2) layout has a nice balance of information, spacing, and readability. Is there any reason why it was discarded?

**Comment by papjul** [comment] 2024-02-16 21:07
> the old Geometric Weather (Screenshot 2) layout has a nice balance of information, spacing, and readability. Is there any reason why it was discarded?

For your device, top spacing is the same in Breezy Weather and Geometric Weather:
![image](https://github.com/breezy-weather/breezy-weather/assets/1449159/fa527f0f-3ab5-4627-92ab-94fda4698478)

(Btw, do you use Geometric Weather version 3.102?)

> removing some detail entries (losing information);
> the old Geometric Weather (Screenshot 2) layout has a nice balance of information

You can't both say you don't want to lose current details information and that you prefer old Geometric Weather design where that information is not present. Removing current details is an option in Breezy Weather and doing that will let you achieve a design similar to Geometric Weather ;)

>     * Screenshot 3 includes
>       
>       1. removing some detail entries (losing information);
>       2. setting this app's DPI to 350 and font scaling to 110% (**root required**);
>       3. scrolling up a bit (manually, every time);
>       
>       
>       * And this tweak of display settings also affects the widget, so it's not really a solution.

You don't need to do 2 and 3, just remove all details from header details in settings, and you will see hourly chart, just like you did in Geometric Weather.

**Comment by ludles** [comment] 2024-02-16 21:45
> > the old Geometric Weather (Screenshot 2) layout has a nice balance of information, spacing, and readability. Is there any reason why it was discarded?
> 
> For your device, top spacing is the same in Breezy Weather and Geometric Weather: 
> You even save more spacing than in Geometric Weather by not having the "Refreshed at" on top of hourly forecast card ;)
> 
> > removing some detail entries (losing information);
> > the old Geometric Weather (Screenshot 2) layout has a nice balance of information
> 
> You can't both say you don't want to lose current details information and that you prefer old Geometric Weather design where that information is not present. Removing current details is an option in Breezy Weather and doing that will let you achieve a design similar to Geometric Weather ;)
> 
> > ```
> > * Screenshot 3 includes
> >   
> >   1. removing some detail entries (losing information);
> >   2. setting this app's DPI to 350 and font scaling to 110% (**root required**);
> >   3. scrolling up a bit (manually, every time);
> >   
> >   
> >   * And this tweak of display settings also affects the widget, so it's not really a solution.
> > ```
> 
> You don't need to do 2 and 3, just remove all details from header details in settings, and you will see hourly chart, just like you did in Geometric Weather.

OK, for a fair and direct comparison, I left the "Wind" detail entry to match the "air quality" in Geometric Weather. Without doing 2 and 3, here is how it looks like:
![Snipaste_2024-02-16_16-23-46](https://github.com/breezy-weather/breezy-weather/assets/37469405/21c48055-3d9e-41f6-922a-0977108bd197)

**The difference is: I could see most of the first chart in the Geometric Weather layout, but not any chart in the current version.** 

I hope this is not the intended behaviour. 

If so, there are several ways to improve. I can only think of better responsive top spacing, more compact detail entries, and smaller font sizes. But I am sure you can deal with it better. 

(I am also satisfied with the position of temperature in the Screenshot in README, where the number slightly overlaps with the outer rim of the clouds on top.)

**Comment by papjul** [comment] 2024-02-16 23:55
> OK, for a fair and direct comparison, I left the "Wind" detail entry to match the "air quality" in Geometric Weather.

Fair, really? Your comparison is totally biaised:
- I told you to remove current details, you add more. You can't say "I will replace that small text no one read by two items that are now more visible and then complain they take too much space". Unless having a text bulletin is more important to you than seeing that chart you keep wanting to see? In either case, I won't bring that small text back as I don't believe that's a good experience at all. But if you really can't live without it, have a look at the custom subtitle feature available on some widgets, so you can have both:
![IMG_20240216_234751](https://github.com/breezy-weather/breezy-weather/assets/1449159/cd9fb215-8589-4dd0-9f78-a5714a3bfba9)

- I asked you in my previous message if you were really using latest version of Geometric Weather, and you keep using an old version of Geometric Weather for your comparisons, before it added Temperature/Air quality/Wind/etc tabs, so you save space in your comparison. Unless what you're asking for is to remove these tabs that were implemented back in Geometric Weather, in that case that's a no, I'm not going to remove very useful features.
- I don't know if that's because you use an old version that didn't support it, or because you use a weather source that doesn't have hourly bulletin, so you save even more space in the Geometric Weather by not having that subtitle under Hourly forecast title. That subtitle should appear on both screenshots for fair comparison.

Anyway, we have strong disagreements on how to compare comparable things and what matters, and many suggestions were given to customize your home screen or widgets to your needs, so issue will be closed. If that still doesn't fit your needs, you're free to keep using that old version of Geometric Weather or have a look at other weather apps ;)

**Comment by ludles** [comment] 2024-02-17 21:35
OK, I see your point now. @papjul  I apologise for having missed the details you mentioned (including subtitles/tabs/different data sources), and I acknowledge that my previous comparison is biased.

I greatly appreciate and respect your efforts in maintaining this project, and I do like many of the new features you have added. The precipitation forecast chart below the hourly chart is one of my favourites. I do not ask you to remove any features.

(To answer your concern about the versions, I used https://github.com/WangDaYeeeeee/GeometricWeather/releases/latest, which leads to GeometricWeather 3.013. I did not use the 2 pre-release versions.)

---

Anyhow, the biased comparisons with GeometricWeather aside, (which were never intended to be the subject of this issue), here I am only bringing up the fact that the layout is probably not working as expected. I removed the detail entries as you asked (although the chart is still not visible 😢), and included the following figure:

![Snipaste_2024-02-17_16-31-58](https://github.com/breezy-weather/breezy-weather/assets/37469405/e8dfff5f-4b46-4d00-872a-efd6cee97715)

To me, it looks like the detail entries on your device push up the temperature number? Although I am not sure how it changes on your device.

I wonder if it is possible to get the layout as in the Screenshot in README (the Demonstrated behaviour above), where the position of the temperature number slightly overlaps with the outer rim of the clouds on top? 

Or in other words, when the device is smaller, could it prioritise presenting information over spacing?

**Comment by papjul** [comment] 2024-02-17 22:06
> The precipitation forecast chart below the hourly chart is one of my favourites.

Credits goes to Wangdaye! That's the last feature he implemented but never released (not even as beta).

> I wonder if it is possible to get the layout as in the Screenshot in README (the Demonstrated behaviour above), where the position of the temperature number slightly overlaps with the outer rim of the clouds on top?

I didn't make that screenshot. I think the person who did scrolled down just a bit to get this behavior.

Note that the current details in header are redesigned in next version (this won't change anything to your issue of not seeing first card entirely):
![image](https://github.com/breezy-weather/breezy-weather/assets/1449159/fa97cc9a-5d03-4908-97f7-9b13018acd3c)

To clarify:
- Geometric Weather behavior (at least latest committed code, which is what I forked) is that the first card begins at 66% of the height of your device. Above 66% of the screen, you get the temperature, some text, and everything else is filled with spacing.
- Breezy Weather behavior is that the temperature begins at 30% of the height of your device. This fixes an issue when device is too small on landscape and temperature + text was "squeezed" between top bar and first card. The calculation changed and in the end, it reduced the spacing on all devices in portrait mode.

If you have a small device, or if you set up your accessibility to big display or big font size, you might not be able to see the entirety of the first card. If you look at #86, you will see that some people don't even see the first card at all. Nothing surprising then.

In the end, big screen or not, even if you can see the entirety of the first card, there are many other cards down there, so your finger will scroll anyway to look for other information, it's just a matter of a few microseconds.

Your "expected behavior" doesn't fit the design of Breezy Weather. It lacks breathing which feels oppressive to exaggerate a bit. And when scrolled, the background animation fades out. Both are not things I want users to experience, even as an option.

I reduced the 30% to 25% for next version, that's the best I can concede on this matter.

**Closed** 2024-02-17 22:06 UTC
Labels: Idea, Wontfix, Reproducible in Geometric Weather, Workaround

**Comment by ludles** [comment] 2024-02-17 23:25
Thanks a lot for the clarification and pointing to #86 !  I agree with your design concept, and I think beginning at 30% or 25% of the screen height makes good sense. 

I took the liberty of stitching the screenshot in https://github.com/breezy-weather/breezy-weather/issues/86#issuecomment-1611675417 into the ones above: 
![Snipaste_2024-02-17_17-34-16](https://github.com/breezy-weather/breezy-weather/assets/37469405/0968b5ed-c2a2-4d42-b784-29da599ddf03)

I roughly measured the height (sorry, I do not know how to measure properly), but it begins at around 40% on my device, and obviously less than 30% (roughly at 20%) on the last screenshot. I wonder if this is expected, or if I misunderstood the height calculation? 

I am not familiar with Android app developing, but would be willing to help with further testing. Please let me know if you need more information to identify or fix this (if it indeed needs fixing). 

(BTW, the default behaviour in https://github.com/breezy-weather/breezy-weather/issues/86#issuecomment-1611675417 (the last screenshot above) would actually solve my case.) 

> In the end, big screen or not, even if you can see the entirety of the first card, there are many other cards down there, so your finger will scroll anyway to look for other information, it's just a matter of a few microseconds.

I personally cannot agree on this point. I hope the first page gives me the most interesting information. and sometimes I can just close the app without scrolling further. But I understand that this differs according to users' habits.

> Note that the current details in header are redesigned in next version

This looks great! Concise and informative. Very neat improvement. Looking forward to the next update.

**Comment by papjul** [comment] 2024-02-18 00:16
Why is your total height 886 px while your device mentions 1920? It's true that it's not exactly 30% with the way you measured, because there is a spacing margin above the temperature, so that when you scroll the "0 min ago" doesn't touch the temperature. So I'm pretty confident in the calculation. If there weren't these margins, I would have put ~38% instead of 30% to match a similar result as Geometric Weather.

> I hope the first page gives me the most interesting information. and sometimes I can just close the app without scrolling further.

But if you're only interested in hourly forecast and don't plan on scrolling further, opening the app is not the most efficient way to access that info.

Just add one of the two hourly widget. That way, you can see the entire chart and you don't even need to open the app.
- "Material You - Forecast" in 4x4 format contains current summary, hourly and daily in a compact format.
- "Hourly trend" has the hourly forecast as a chart in 2x4 format.

**Comment by ludles** [comment] 2024-02-18 01:19
> Why is your total height 886 px while your device mentions 1920? 

Because it was measured on my monitor after being resized.

> It's true that it's not exactly 30% with the way you measured, because there is a spacing margin above the temperature, so that when you scroll the "0 min ago" doesn't touch the temperature. So I'm pretty confident in the calculation. 

Oh, I see what you mean. A long press on the temperature shows the bounding box, that is where 30% from the top is calculated. Thanks for the explanation. Then in this case I agree with your change to 25%, or even 20%, thanks to the extra margin space.

So does this mean https://github.com/breezy-weather/breezy-weather/issues/86#issuecomment-1611675417 shows the behaviour of an outdated version? Because if calculated in this way, it must be even less than 20%.

> This fixes an issue when device is too small on landscape and temperature + text was "squeezed" between top bar and first card. 

Would a left(main info)/right(charts) panel layout be more suitable for landscape mode?

> Just add one of the two hourly widget. 

Sadly the "Material You" does not change at all for me. I assume my Android version is too low to be compatible. And I already have the daily trend widget taking up all my desktop space. Anyway, thanks for your suggestions.

**Comment by papjul** [comment] 2024-02-18 07:35
> Would a left(main info)/right(charts) panel layout be more suitable for landscape mode?

There are two landscape cases: small screen, in that case there is not much more we can show, but we do show a bit more of each chart. Not sure a lot of people use landscape on small devices, except when they play video games. The second case is tablet where there is more space, in that case we (optionally) show the location list on the left for easy switch between locations.

In either case, having to scroll from left to right to navigate between cards would be very confusing, especially as inside some cards you also have to scroll from left to right.

> So does this mean [#86 (comment)](https://github.com/breezy-weather/breezy-weather/issues/86#issuecomment-1611675417) shows the behaviour of an outdated version?

If you mean that you found screenshots in an old issue where we see temperature stuck on top with no spacing, then yes, this version broke Geometric Weather behavior. This bug was fixed with a different technical reimplementation as mentioned in my previous message.

> Sadly the "Material You" does not change at all for me.

What do you mean "does not change"?

**Comment by ludles** [comment] 2024-02-19 03:48
Thanks a lot for your explanation!

I think the current design for big screens is good. I was thinking about small screens, where the left panel can be fixed to show the main info, and the right panel includes the charts and the scrolling is still vertical (up-down). But as you said, I also don't think a lot of people use landscape on small devices, so I am not sure if this is worth implementing.

> > Sadly the "Material You" does not change at all for me.
>
> What do you mean "does not change"?

It means the content of the "Material You" widget remains the same regardless of the size. I assume Android version > 12 is required for this feature. So I am not surprised. But if you think this might be a bug, I can open another issue to show more.

**Comment by papjul** [comment] 2024-02-19 12:29
It should create a fixed 4x3 widget on Android < 12. But I can't even find the widget in the list on an Android 5.0 device, I'm not sure why.
