### ISSUE TITLE
Settings freeze after restart via snackbar or theme change

### ISSUE THREAD

**Issue by min7-i** [breezy-weather/breezy-weather#717] opened 2024-02-27 15:55 UTC
### Steps to reproduce

1. Go to settings -> Appearance.
2. Change the dark mode from light to dark or vice-versa.

Alternatively, you can also trigger a restart via
1. Settings -> Language.
2. Change the language.
3. Tap on 'Restart' in the snackbar.

### Expected behavior

The change is applied and the app normally reacts to inputs.

### Actual behavior

The change is applied, but the app UI freezes. It's only possible to navigate back via the Android back navigation button / gesture. After navigating back the app reacts normally again.

### Weather source used

N/A

### Breezy Weather version

5.0.1-alpha

### Android version

Android 14 (GrapheneOS)

### Device

Google Pixel 6a

### Other details

On my device the issue is identical to the one described in #452 and there is no difference between 4.6.14-beta and 5.0.1-alpha.

I also tried both versions on my LG G6 (Android 9) and it's working fine in both.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2024-02-27 16:11
I think issue in #452 was that in v4.6.6-beta, the issue was that it was not responding to anything: the back button didn't work at all back then. I can reproduce your test, indeed, I always use the back button after a change, that's why I didn't notice ;)

If it works normally in v4.6.5-beta, I'm pretty sure it's a regression from a dependency (or maybe the Breezy Weather implementation of the dependency is incorrect, and it was not leading to issues before, but now it does).

**Comment by min7-i** [comment] 2024-02-27 17:15
I went back and tried a few of the old versions. It works until 4.6.4-beta and stops working in 4.6.5-beta. Although I haven't tested all of the versions afterwards.

> [...] in https://github.com/breezy-weather/breezy-weather/issues/452 was that in v4.6.6-beta, the issue was that it was not responding to anything: the back button didn't work at all back then.

The actual behavior and workaround mentioned in that issue sound identical to what I'm experiencing on my device right now.

Just to be sure that we're talking about the same back button. I mean this one (red rectangle) and not the one in the top app bar:
<img src="https://github.com/breezy-weather/breezy-weather/assets/97251923/323ca752-0a6a-4bbc-97cb-af960bb325a4" width=50%>

**Comment by Cod3dDOT** [comment] 2024-03-02 05:12
It seems identical. I used "swipe back", which is identical to pressing the android back button. In hindsight, I should have worded that better.

**Comment by ecawthorne** [comment] 2024-07-23 21:55
This can also be reproduced from the main screen by going to edit location > global settings > make and change that requires the snackbar. The only difference is instead of freezing on the settings screen it freezes on the "Main screen" in this instance.

**Comment by ecawthorne** [comment] 2024-09-10 14:45
> I think issue in #452 was that in v4.6.6-beta, the issue was that it was not responding to anything: the back button didn't work at all back then. I can reproduce your test, indeed, I always use the back button after a change, that's why I didn't notice ;)
> 
> If it works normally in v4.6.5-beta, I'm pretty sure it's a regression from a dependency (or maybe the Breezy Weather implementation of the dependency is incorrect, and it was not leading to issues before, but now it does).

This seems to have been fixed in 2d7afa3. So most likely a regression?

**Comment by ecawthorne** [comment] 2024-09-10 15:22
> Looks like it's much better. I still experience an unresponsiveness for a few seconds after changing the "Background animation" preference (from Main screen settings) and tapping "Restart". The main settings page can be scrolled but tapping on any subpages doesn't work for a few seconds.

I can't reproduce this consistently for some reason. Sometimes it works as intended (aside from kicking us back into the root settings screen after config changes) and sometimes it's unresponsive. The snackbar appearing when a restart is needed can be inconsistent as well.

**Comment by min7-i** [comment] 2024-09-20 19:34
> The snackbar appearing when a restart is needed can be inconsistent as well.

@ecawthorne I identified the cause for this issue. With #1318 this should now work reliably.

**Comment by papjul** [comment] 2024-10-11 11:14
Fixed with #1336

**Closed by papjul** 2024-10-11 11:14 UTC
Labels: Bug, Priority: low
