### ISSUE TITLE
If you go into the settings and then into a menu and then hit the error to go back it will leave the settings completely.

### ISSUE THREAD

**Issue by peaklabs-dev** [breezy-weather/breezy-weather#279] opened 2023-08-01 15:13 UTC
### Steps to reproduce

1. Click on Settings
2. Open for example the notification option
3. Press the back button (arrow) at the top left.
-> This will take you out of the settings and back to the weather.

### Expected behavior

It should only go back 1 point in the menu and return you to the settings page.

### Actual behavior

Goes straight to the weather page 

### Weather source used

AccuWeather

### Breezy Weather version

4.4.1-beta

### Android version

Android-13

### Device

Google Pixel 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment] 2023-08-01 15:19
Duplicate of #53

**Closed as not planned by papjul** 2023-08-01 15:19 UTC
Labels: Bug, Duplicate
