### ISSUE TITLE
[China] Incorrect text in hourly forecast when locale is not Chinese

### ISSUE THREAD

**Issue by cliuff** [breezy-weather/breezy-weather#1091] opened 2024-06-06 09:07 UTC
### Steps to reproduce

1\. Set app language to non-Chinese
2\. Add a location that is currently raining, set weather source to China

### Expected behavior

The hourly forecast section should display correct precipitation description

### Actual behavior

The hourly forecast section displays precipitation description with inapporiate distance placeholder in it.
<img alt="App screenshot" src="https://github.com/breezy-weather/breezy-weather/assets/35420834/3b6f129e-8f09-4381-9066-246fac595b41" width="270" />

### Weather source used

China

### Breezy Weather version

5.2.4

### Android version

Android 13

### Device

Google Pixel 4

### Other details

I have pulled the source code and investigated the issue. In conclusion, it is due to the terrible locale support of the Chinese weather API for non-Chinese languages. I suggest forcing `locale = "zh_cn"` for `org.breezyweather.sources.china.ChinaApi#getMinutelyWeather`.

From the screenshot of Chrome below, we can see correct precipitation desc with `locale=zh_cn` in the weather API:
![db5b434a-05a9-495a-8516-f9ddc933e8e8](https://github.com/breezy-weather/breezy-weather/assets/35420834/9219a2ba-6fef-4c6c-8ecf-b5e7ddfd0aab)
However, precipitation desc is still in Chinese plus an inapporiate distance placeholder with `locale=en_us`:
![48240f4b-eb26-401c-8dbb-9edf6b80de98](https://github.com/breezy-weather/breezy-weather/assets/35420834/9585257e-cf1e-4cdc-b861-c08c67c1e23c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2024-06-08 07:54
I have a fix on this branch: https://github.com/breezy-weather/breezy-weather/tree/fix_1091

However, I can't reproduce at the moment. Even using a radar, I had a hard time finding a city with rain, and when I found one, it didn't have any description.

**Comment by cliuff** [comment] 2024-06-08 10:12
It is easy to find raning cities on [weather.com.cn](http://www.weather.com.cn/radar/) as shown in screenshot below. You can search the Chinese name in the app witḣ search source set to China.
<img width="600" src="https://github.com/breezy-weather/breezy-weather/assets/35420834/2e2e0197-6e60-4d51-b267-a286f460f790" />

**Comment by cliuff** [comment] 2024-06-08 10:58
I can confirm that language code "zh_cn" or simply "zh" works, while "zh-cn" does not.

<img width="700" src="https://github.com/breezy-weather/breezy-weather/assets/35420834/948afe8a-730a-4307-ba25-6d866674b1d8" />

<img width="700" src="https://github.com/breezy-weather/breezy-weather/assets/35420834/ebb00d31-db52-4585-b8cb-a9e4472381a2" />

**Comment by papjul** [comment] 2024-06-11 10:27
> I can confirm that language code "zh_cn" or simply "zh" works, while "zh-cn" does not.
> 
> <img alt="" width="700" src="https://private-user-images.githubusercontent.com/35420834/337869341-948afe8a-730a-4307-ba25-6d866674b1d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMDE4ODYsIm5iZiI6MTcxODEwMTU4NiwicGF0aCI6Ii8zNTQyMDgzNC8zMzc4NjkzNDEtOTQ4YWZlOGEtNzMwYS00MzA3LWJhMjUtNmQ4NjY2NzRiMWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDEwMjYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNzIwN2ZhNTE2NjJmMzgzMzc0ZDBmZDAwYTA5ZWZmOTc5NDY3YWNhYjg0ZTNlZWQ2ZTA2ZTBlM2I0OGVlOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lM0PjSjAeXwGiutLF_T-Kqz22NyrodpeKlILCKIZiPE"> <img alt="" width="700" src="https://private-user-images.githubusercontent.com/35420834/337869347-ebb00d31-db52-4585-b8cb-a9e4472381a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMDE4ODYsIm5iZiI6MTcxODEwMTU4NiwicGF0aCI6Ii8zNTQyMDgzNC8zMzc4NjkzNDctZWJiMDBkMzEtZGI1Mi00NTg1LWI4Y2ItYTllNDQ3MjM4MWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDEwMjYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhYzI1YjQ0MDk2ZmIxYTNjZGU5YmJhZjI2YzhiODc1MzljZjUyNzQwZjU2NTRlYTk1OWE2ZmY2MGM1NGI3ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B9H844OmtgqavYH17g8KutK4Ui5rJTd-3LRR2iq4XmQ">

Fixed in 43220193487251d6a59b5674103ceae0f1564379

**Comment by min7-i** [comment] 2024-07-19 17:42
Hasn't this been resolved by the commit mentioned in the comment above?

**Comment by papjul** [comment] 2024-07-19 18:08
No, it's a different issue. The fix for this issue is in a branch that is not merged: https://github.com/breezy-weather/breezy-weather/tree/fix_1091

The issue is that I cannot find a city affected by this issue, even by following given instructions.

**Comment by PumpkinJui** [comment] 2024-08-03 05:30
I can't reproduce this issue in the app, either.

When it is rainy in/near the target location, with Simplified Chinese or Traditional Chinese used, it seems alright:

(This is Beijing, China)
![Nearest Precipitation, Simplified Chinese](https://github.com/user-attachments/assets/a0aad1a3-85f8-4f48-815c-a2478ea0e6f6)
![Nearest Precipitation, Traditional Chinese](https://github.com/user-attachments/assets/a505f4bf-2cdc-4970-8a07-55305e70c4eb)

(And this is Luochuan, Yanan, Shannxi, China)
![Rain Shopping, Simplified Chinese](https://github.com/user-attachments/assets/e6099b44-f7d0-4df5-9b97-bf88dc00dc3d)
![Rain Stopping, Traditional Chinese](https://github.com/user-attachments/assets/bd777930-e7ae-44b1-995a-f90b34af524b)

But switched to English, it shows the same thing when not refreshed, and disappears immediately on refreshing:

![Beijing](https://github.com/user-attachments/assets/7cb42f5d-1784-4dcf-bca7-4a1e1b4a5f2e)

![Luochuan](https://github.com/user-attachments/assets/708b015b-65be-4b76-89da-1d6dfcfd8ad7)

Additionally, I think there's nothing to do with Traditional Chinese in this issue, so the title could be inaccurate.

**Comment by papjul** [comment] 2024-08-03 06:21
Yes, sorry, it was with non-Chinese locales. I can't seem to find any place with precipitation. After a few tries, it looks like after using an IP from Hong Kong I was able to find one place but precipitation ended soon.

@cliuff can you confirm if the issue is still there?

**Comment by cliuff** [comment] 2024-08-09 12:43
Apparently the forecast description field has been cleared for non-Chinese languages.

![Screenshot 2024-08-09 213413](https://github.com/user-attachments/assets/71a249c8-1824-4e30-9a56-1c1f5ef53b97)
![Screenshot 2024-08-09 213250](https://github.com/user-attachments/assets/77d77234-fef7-42df-a248-c94851924868)

**Comment by papjul** [comment] 2024-08-09 13:27
Thank you, it's indeed better they fix it on their side :)

**Closed by papjul** 2024-08-09 13:27 UTC
Labels: Bug, Needs more info, Dependency issue
