### ISSUE TITLE
Temperature in status bar is stretched

### ISSUE THREAD

**Issue by Coffee-Viking** [breezy-weather/breezy-weather#499] opened 2023-10-02 07:18 UTC
### Steps to reproduce

1. Enable "show temperature as status bar icon"
2. See wrong font (larger and different type)

### Expected behavior

Font type and ideally size to follow system

### Actual behavior

Type is random, size larger than the rest

### Weather source used

Tried all, no change

### Breezy Weather version

4.6.7-beta

### Android version

Android 12 (Stock OxygenOS - OnePlus default)

### Device

OnePlus 10 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by Coffee-Viking** [comment] 2023-10-02 07:18
![IMG_20231001_183629](https://github.com/breezy-weather/breezy-weather/assets/12423506/7fe1a74a-391b-497f-87b8-c4c2aca8ccfe)

Left geometric weather, right breezy weather.

**Comment by papjul** [comment] 2023-10-02 07:46
I'm also using Android 12 and I don't have this problem. It looks like an OxygenOS customization. Will leave open to contributions as it is unsure if a fix is possible, and even if it is possible, I would be unable to test it.

**Comment by min7-i** [comment] 2024-02-20 22:53
@Coffee-Viking Are you using the OxygenOS stock launcher or a third-party app? Normally, the font set on your device should already be used for the temperature in the status bar. Although it's weird that the clock in your screenshot seems to have a different font.

It would be great if you could try to change the font in your system settings to see if the font for the temperature changes. If I'm not mistaken, that should be possible in OxygenOS 12 and newer via the settings app. _(You'll have to deactivate and reactivate the setting to show the temperature in the status bar in Breezy Weather to apply the new font.)_

If the font of the temperature in the status bar changes, could you provide a screenshot of that?

**Comment by min7-i** [comment] 2024-03-09 10:13
@Coffee-Viking Thanks for testing.

Could you try again with the latest release v5.1.0-beta? We switched to a fixed font instead of using the system font set on the device. With the new font the text should hopefully be less stretched on your device as well.

It should be similar to the left temperature icon shown here:
<img src="https://github.com/breezy-weather/breezy-weather/assets/97251923/ecd73c58-3493-4dc3-aded-72198df46dd6" width=50% />

**Comment by Coffee-Viking** [comment] 2024-03-09 23:01
![Screenshot_2024-03-10-06-58-13-25_3822ac0e29cfec8970059bb21d01f05e_1](https://github.com/breezy-weather/breezy-weather/assets/12423506/df1b2197-4346-433d-afc3-0742b8ba06b4)

It looks similar indeed, just a bit more massive somehow. Is there a way to use a smaller font size, or user defined font face?

**Comment by papjul** [comment] 2024-03-10 07:25
We have to make something that is visible enough for all devices, and I'm not going to make the app bigger by bundling multiple fonts in the app for user to choose. You can check previous discussions in #606 with differences between a few tested fonts and that one was the only one visible enough, especially with 2 digits.

I can see the issue is fixed, so I will proceed to close it.

**Closed by papjul** 2024-03-10 07:25 UTC
Labels: Bug, Needs more info, Device-specific
