### ISSUE TITLE
[Clock widget] Allow redirect to another clock app tab

### ISSUE THREAD

**Issue by d-faure** [breezy-weather/breezy-weather#952] opened 2024-04-16 06:25 UTC
### Describe your idea

Hi, for now on a Samsung A34, touching the clock text of a widget redirects you directly to the Alarm sub tab of the regular clock application.
Couldn't this be parametrized and allow at least to go to the main Clock screen or another clock application?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] The idea I’m suggesting is not in the [list of features that will not be implemented](https://github.com/breezy-weather/breezy-weather/blob/main/README.md#features-that-will-not-be-implemented).
- [X] I have written a short but informative title.
- [X] I have updated the app to **[version 5.2.0 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2024-04-16 06:31
Duplicate of #648, it's a Samsung bug

**Closed by papjul** 2024-04-16 06:31 UTC
Labels: Idea, Needs review

**Comment by papjul** [comment] 2024-04-16 07:14
Please ensure you report the issue to Samsung, or they will never fix it!
