### ISSUE TITLE
Truncated text widget display

### ISSUE THREAD

**Issue by Sami32** [breezy-weather/breezy-weather#1011] opened 2024-04-26 09:01 UTC
### Steps to reproduce

2x1 widget display

![IMG_20240426_102407](https://github.com/breezy-weather/breezy-weather/assets/18471069/56e7f5ad-8b54-4da6-b5c8-c2cf667f8a63)

### Expected behavior

Do not truncated the widget display.

### Actual behavior

The 2x1 widget truncate the display.

### Weather source used

Meteo France

### Breezy Weather version

5.2.2 freenet

### Android version

Google Android 7.0

### Device

Xiaomi Redmi Note 4

### Other details

Worked fine 2 versions ago.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.2 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2024-04-26 09:21
It's up to you to define the constraints of the widget, you can extend its height easily.

> Worked fine 2 versions ago.

What do you mean exactly? Can you show a screenshot of v5.2.0, showing the constraints of the widget (as if you want to resize it)?

> ### Weather source used
> 
> Meteo France
> ### Breezy Weather version
> 
> 5.2.2 freenet

This has nothing to do with this issue, but this is not valid. Make sure to double check your other informations.

**Comment by Sami32** [comment] 2024-04-26 09:38
My F-Droid version updated now with Obtnainium so perhaps it became "Standard"?

No info about Standard or freenet seem showing in your About tab or Android App info.
![Screenshot_2024-04-26-11-29-27-746_org breezyweather](https://github.com/breezy-weather/breezy-weather/assets/18471069/9701dedd-c358-49ec-a42e-0add1631425f)
![Screenshot_2024-04-26-11-33-03-550_org breezyweather](https://github.com/breezy-weather/breezy-weather/assets/18471069/13837d33-6a78-41ce-949e-09b8f3de3b50)

No i don't have the prior working version snapshot but since your App widget are now different without any change from my side...i'll try to find widget setting that can fix it or revert back.

Thanks

**Comment by papjul** [comment] 2024-04-26 09:42
> My F-Droid version updated now with Obtnainium so perhaps it became "Standard"?

If you didn't tell Obtainium to use a specific version, it will use standard. Your screenshot shows 5.2.2, which is the standard version. Only the `freenet` flavor has a version suffix.

> No i don't have the prior working version snapshot but since your App widget are now different without any change from my side...i'll try to find widget setting that can fix it or revert back.

You can download v5.2.0 here: https://github.com/breezy-weather/breezy-weather/releases/tag/v5.2.0

There was no change to the text widget in v5.2.1 or v5.2.2, so I'm surprised that something would have changed. Even in previous versions, we only added the ability to have a custom subtitle, but without changing the other elements size.

**Comment by Sami32** [comment] 2024-04-26 10:20
Uninstalling and reinstalling 5.2.0 the upgrade to 5.2.2 freenet now work fine.
Yes the 5.2.0 was still fine.

Perhaps 5.2.1 was the one that missed thing up when custom text was added or the widget extended to 2x2?

In any case, now it work. Thanks.

**Comment by papjul** [comment] 2024-04-26 10:35
I think your launcher had a temporary issue and removing the widget and re-adding it would probably have fixed it.

**Comment by Sami32** [comment] 2024-04-26 13:40
Then my launcher issue will only affect your widget?
I never saw this issue before and only test your App since few days

Perhaps a sneaky issue in your custom subtitle code?

**Comment by papjul** [comment] 2024-04-26 15:05
If you cannot reproduce, it has nothing to do with the custom subtitle, since the custom subtitle was present in v5.2.0, v5.2.1 and v5.2.2.

Android 7.0 is very old, I believe a lot of issues have been fixed in almost 10 years. You're not the first person to report an issue that only affects old Android versions.

**Comment by Sami32** [comment] 2024-04-26 20:31
Roproduced after removing and reinstalling the widget:
![Uploading IMG_20240426_222937.jpg…]()

**Closed** 2024-04-26 20:36 UTC
Labels: Bug, Invalid, Needs more info, Regression

**Comment by papjul** [comment] 2024-04-26 21:19
I don't understand what you want me to do. If you change the font size and it no longer fits, maybe don't change the font size or make the widget have a higher height?
