### ISSUE TITLE
Please add tomorrow weather api

### ISSUE THREAD

**Issue by androidghosh** [breezy-weather/breezy-weather#905] opened 2024-04-08 03:28 UTC
### Link to publicly available documentation of the API

https://www.tomorrow.io/weather-api/

### Available and not available data

Free version has this available:
5-Day Forecast
Weather Timelines and Trendlines
Weather API Access
Core Weather Data Layers
Industry-Based Insights Templates
24 hours Historical Weather Data
1 Automatically monitored Location
1 Weather-Based Alert

### Are you going to develop yourself the new source for the app?

No, not a developer, keep it open to contributions

### Give a bit more details or context about this source

In my experience this source is lot better in forecasting than others. At least for my location.

### Acknowledgements

- [X] This source has a free-tier available (no mandatory credit card info and trials don’t count as “free”), and if it is a main weather source, it includes free hourly forecast
- [X] If this is a weather source request, I checked that endpoints are by coordinates, or that there is a reverse geocoding endpoint.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written the name of the source as the title of this issue.
- [X] I have updated the app to **[version 5.1.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and this source is not part of it.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2024-04-08 05:20
Duplicate of #469

**Closed by papjul** 2024-04-08 05:20 UTC
Labels: New source, Needs review
