### ISSUE TITLE
Also show time on precipitation forecast when tapping on graph

### ISSUE THREAD

**Issue by Fxsch** [breezy-weather/breezy-weather#841] opened 2024-03-23 12:31 UTC
### Describe your idea

When tapping on the precipitation forecast graph, it will show how much mm/h are coming down at that time point. It would be helpful if it also showed the time at that point in addition because it's not easy to tell just by the hourly time points that are under the graph. That way, you could easily tell at what exact time it will rain a certain amount or start/stop raining.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 5.1.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2024-03-23 12:57
Duplicate of #369 and #687

**Closed by papjul** 2024-03-23 12:57 UTC
Labels: Idea, Needs review
