### ISSUE TITLE
Add exact time to precipitation forecast slider

### ISSUE THREAD

**Issue by KlimaRitter** [breezy-weather/breezy-weather#315] opened 2023-08-07 06:42 UTC
### Describe your idea

The preciptation forecast is very nicely done, and the slider shows the expected rainfall amount which works great.
However it would be nice, if it also showed the exact time at the position of the slider, or maybe the minutes from now (like in 30 min, in 46min ).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to an existing feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment] 2023-08-07 07:34
Looks a lot like #187 

I think sources advertise this as a minute by minute precipitation forecast, but this is probably not as accurate. "46 minutes" can probably become 41 min or 51 min or "won't happen actually, we were wrong".

Especially after a few tests, I seemed to notice that for example AccuWeather is showing the precipitation forecast for the whole town, not for your coordinates (even if you use "current location"), although the precipitation can be very different at different spots of the town.

So, just to say it is not precise to the minute, so you don't need to have the "in 46 minutes" info. Legend on X-axis is probably enough to make an estimation to when it will roughly happen.

**Comment by KlimaRitter** [comment] 2023-08-07 09:35
AccuWeather is showing it for the exact location, if you have premium. I don't know how it works with the API, but a quick look at https://developer.accuweather.com/ suggests that it should also work wiht the API:
**
![image](https://github.com/breezy-weather/breezy-weather/assets/54468603/e0ae626f-4362-4307-a4e7-05bd04060a40)
**

**Comment by papjul** [comment] 2023-08-07 10:52
I know that AccuWeather has an endpoint by longitude/latitude, what I'm saying is that it will just get the precipitation forecast for the closest city. That's what I found when "fake travelling" to different points of a large city, they all returned the exact same 120 minutes forecast.

Btw, the API documentation you're showing is not the one we use as it has no precipitation quantity.

**Comment by KlimaRitter** [comment] 2023-08-07 10:54
OK I see, thanks for your great work anyways :)

**Comment by papjul** [comment] 2023-08-08 18:53
After reviewing with other project members, I will look into it when modernizing the precipitation graph, if I can easily do something to add it.

I will also not consider this issue as duplicate of #187.
#187 contains two ideas so let's track the "exact time" idea here, and the other on #187.

**Comment by papjul** [comment] 2023-08-15 14:46
This will be done as part of #369

**Closed by papjul** 2023-08-15 14:46 UTC
Labels: Idea
