### ISSUE TITLE
Your current location name

### ISSUE THREAD

**Issue by fearmusa** [breezy-weather/breezy-weather#467] opened 2023-09-13 17:59 UTC
### Describe your idea

For example, in the weather.io application, the current location address is available in the notification line.
![Screenshot_20230913-203106_Weather](https://github.com/breezy-weather/breezy-weather/assets/127376654/e43b6a2a-dec0-4153-9249-fecc4c67d69f)

Information such as instant location information, address and street are included in the notification line. It looks better where you are than where you are.

### Other details

Samsung a70 
![Screenshot_20230913-205800_Settings](https://github.com/breezy-weather/breezy-weather/assets/127376654/2b1d3496-2425-40af-837e-2491613b5863)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.5 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2023-09-13 18:29
Which notification are you talking about?

**Comment by fearmusa** [comment] 2023-09-14 03:38
Hello again. The image above is in the picture I sent. Notification type of Breezy application. I use open-meteo. In the continuous notification section provided by the Brezzy application. Can the location received by GPS be written instead of "Current location"? Just like in the Weather.io app. So instead of "current location",Can location information be written? 
![Screenshot_20230914-063505_One UI Home](https://github.com/breezy-weather/breezy-weather/assets/127376654/9ae40d71-3655-40cf-ac5e-808bf8a9a84e)
![Screenshot_20230914-063332_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/127376654/32e06b13-8c3f-4462-9fab-bb0c44a168d2)
![Screenshot_20230914-063323_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/127376654/2fae0ca4-109c-401f-b9a6-6e4090a36e49)

**Comment by papjul** [comment] 2023-09-14 06:39
Duplicate of #417

**Closed by papjul** 2023-09-14 06:39 UTC
Labels: Idea, Needs more info, Needs review
