### ISSUE TITLE
Radar viewer

### ISSUE THREAD

**Issue by bqv** [breezy-weather/breezy-weather#767] opened 2024-03-08 22:39 UTC
### Describe your idea

Any chance of one? I'm not sure how possible this is, but this is the *only* thing missing compared to other apps.

 Example from accuweather: 
![Screenshot_2024-03-08-22-38-17-99_051725baefd68d1e9ddb81affa7511e8](https://github.com/breezy-weather/breezy-weather/assets/822863/6a9dd85f-ac8c-44ee-8c71-71970a8f9426)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 5.0.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2024-03-09 05:52
Duplicate of #23 

Read https://github.com/breezy-weather/breezy-weather/blob/main/docs/RADAR.md

**Closed by papjul** 2024-03-09 05:52 UTC
Labels: Idea, Needs review

**Comment by bqv** [comment] 2024-03-10 02:39
understood, will use Ventusky instead.
