### ISSUE TITLE
Material You widget cuts off, and doesn't open the app when tapped

### ISSUE THREAD

**Issue by Insane-Owl** [breezy-weather/breezy-weather#888] opened 2024-04-04 00:06 UTC
### Steps to reproduce

1. Add the material you themed widget from version 5.1.8 of the app
2. Observe, and tap

### Expected behavior

It should be smaller so it doesn't cut off, and it should open the app when tapped

### Actual behavior

It cuts off, and doesnt open the app when tapped
![Screenshot_20240403-192444_One UI Home](https://github.com/breezy-weather/breezy-weather/assets/78328941/c3f88530-9afc-4cc3-a44d-84f150acab79)
https://github.com/breezy-weather/breezy-weather/assets/78328941/5200b955-26ea-4557-9ff5-2a4b8ea99b2a

### Weather source used

AccuWeather

### Breezy Weather version

5.1.8 fdroid

### Android version

Android 12

### Device

Samsung Galaxy S10e

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.1.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2024-04-04 04:45
Duplicate of #869 and #316

One issue = one bug please

**Closed by papjul** 2024-04-04 04:45 UTC
Labels: Bug, Needs review
