### ISSUE TITLE
The app crashes when switching among the locations

### ISSUE THREAD

**Issue by PumpkinJui** [breezy-weather/breezy-weather#468] opened 2023-09-14 05:40 UTC
### Steps to reproduce

Well I'm not sure. I discovered this by:
1. Make sure you have added at least three different locations.
2. Restart the app.
3. Switch among the locations by scrolling the screen. Each location should be different and no switching back.

### Expected behavior

The locations should always be switched as soon as I do that.

### Actual behavior

When switching to the third one, it crashes. At least I can repro it.

### Weather source used

中国 & AccuWeather

### Breezy Weather version

4.6.5-beta

### Android version

Android 8.1.0

### Device

OPPO R11s

### Other details

https://github.com/breezy-weather/breezy-weather/assets/76104432/e1cf592d-1973-42f7-805d-32567b27a373

[breezyweather_crash_logs.txt](https://github.com/breezy-weather/breezy-weather/files/12605126/breezyweather_crash_logs.txt)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.5 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2023-09-14 06:44
1) What happens when you access the 3rd location from location list?
2) What happens when you access the 3rd location by swiping left on 1st location?

**Comment by PumpkinJui** [comment] 2023-09-14 16:11
> 1) What happens when you access the 3rd location from location list?

Crashes immediately. Only the location name can be seen then flashes away as the screen recording shows.

> 2) What happens when you access the 3rd location by swiping left on 1st location?

Works normally. I don't really understand that, though.

> It seems unrelated to switching as you always reproduce and I cannot.

I can only reproduce the crash by this way. However, it is possible, as in some condition the switching cannot repro on my device neither.
Maybe the crash log can help? I added it under the screen recording, but maybe it just wasn't very easy to be seen...?

**Comment by papjul** [comment] 2023-09-14 16:38
> > 1. What happens when you access the 3rd location from location list?
> 
> Crashes immediately. Only the location name can be seen then flashes away as the screen recording shows.
> 
> > 2. What happens when you access the 3rd location by swiping left on 1st location?
> 
> Works normally. I don't really understand that, though.

That is quite unusual.

It doesn't work:
- From location list
- By swiping in order

It works:
- By swiping in reverse order

Are you sure about that?

> Maybe the crash log can help? I added it under the screen recording, but maybe it just wasn't very easy to be seen...?

I saw it, but it's very verbose and a bit obscure, so I'm trying to understand first if it's a weather data issue or an UI issue.

**Comment by PumpkinJui** [comment] 2023-09-14 17:32
Oops, I didn't really understand the questions and gave wrong answers... I'll answer them again and apologise for that. ~~ *If I made this in the following English reading exam, I would fail as badly as possible.* ~~
Simply speaking, the crash just takes place in the situation that the recording shows. Accessing through the location list won't crash, and from 1st directly to 3rd neither. But 1st->2nd->3rd, it will.
If the app did(not “is doing”) the weather updating before switching, it won't crash neither. But “is doing” will.

**Comment by papjul** [comment] 2023-09-14 18:05
I tried to reproduce on an old phone (Android 5.0) and I had no issue.

I’m sorry, but I really have no idea.

**Comment by PumpkinJui** [comment] 2023-09-15 05:16
Geometric Weather worked normally, and I believe Breezy Weather in the version 4.4.1-beta doesn't have the crash problem. But I have no more idea.

**Comment by papjul** [comment] 2023-09-16 08:15
> Geometric Weather worked normally, and I believe Breezy Weather in the version 4.4.1-beta doesn't have the crash problem. But I have no more idea.

That's interesting, can you install version 4.4.1-beta, and update one version at a time until you pinpoint the version that introduced the bug? As I'm not able to reproduce, I will need your help here ;)

**Comment by PumpkinJui** [comment] 2023-09-19 05:11
After the reinstallation, it doesn't crash now...
Weird, but it seems that the problem is resolved somehow...?
After all, a big thank you for your continuously follow-up.

**Comment by papjul** [comment] 2023-09-19 06:40
Closing as no one can reproduce it anymore.

**Closed by papjul** 2023-09-19 06:40 UTC
Labels: Bug, Needs more info, Regression, Workaround
