### ISSUE TITLE
Spanish weather source: AEMET OpenData

### ISSUE THREAD

**Issue by BenjaDAW** [breezy-weather/breezy-weather#1383] opened 2024-10-27 19:39 UTC
### Link to publicly available documentation of the API

https://opendata.aemet.es/centrodedescargas/AEMETApi

### Available and not available data

Available to verify many data

### Are you going to develop yourself the new source for the app?

No

### Give a bit more details or context about this source

This is the national source for Spain.
I believe, although I am not sure, that AEMET OpenData allows free download of the data.
I think that many users of the app could benefit from being able to enjoy this source.

### Acknowledgements

- [X] I have searched [the existing sources](https://github.com/breezy-weather/breezy-weather/blob/main/docs/SOURCES.md) and [the existing new source requests](https://github.com/breezy-weather/breezy-weather/issues?q=is%3Aissue+label%3A%22New+source%22+no%3Amilestone+-label%3ADuplicate) and this is a new source, **NOT** a duplicate or related to another open OR closed issue.
- [X] This source has a free-tier available (not a trial period), and if it is a main weather source, it includes free hourly forecast
- [X] This source does not require sensitive information (billing info, phone number, etc) to subscribe to the free-tier
- [X] I understand there may be technical limitations that may prevent implementing this source (for example, the lack of coordinates information)
- [X] I wrote my request in English. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2024-10-28 08:16
Duplicate of #1123

**Closed by papjul** 2024-10-28 08:16 UTC
Labels: New source, Needs review
