### ISSUE TITLE
Unit Set to Inches But Description Says CM

### ISSUE THREAD

**Issue by HonestAbe7** [breezy-weather/breezy-weather#617] opened 2024-01-03 23:15 UTC
### Steps to reproduce

Try to change your units if precipitation or snow is coming and it will only show cm; not inches.

### Expected behavior

Should show inches and not cm.

### Actual behavior

![Screenshot_20240103-180855](https://github.com/breezy-weather/breezy-weather/assets/88217236/1a6f6d10-7f4e-4a93-b9b9-6f545173bdfa)

### Weather source used

AccuWeather

### Breezy Weather version

4.6.12-beta

### Android version

Android 10

### Device

LG L355DL

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.13 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2024-01-04 06:11
Duplicate of #78

**Closed by papjul** 2024-01-04 06:11 UTC
Labels: Bug, Needs review
