### ISSUE TITLE
About UI of the main page

### ISSUE THREAD

**Issue by n78** [breezy-weather/breezy-weather#60] opened 2023-06-23 05:27 UTC
### Describe your suggested feature

In the main page, I think the original Geometric Weather's UI is more beautiful. If you can change it back (or add an option) it will better.

![IMG_20230623_131931](https://github.com/breezy-weather/breezy-weather/assets/45787455/9727b714-8c83-4c93-967f-a69e8c85afec)
![IMG_20230623_132008](https://github.com/breezy-weather/breezy-weather/assets/45787455/833f3398-34bc-48f9-bb1d-7899a470424d)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment] 2023-06-23 06:05
It's not black or white, I think you need a bit more than a few hours to get used to a new design ;)

The goal of this new design is to allow people to see more details about current weather conditions while keeping the background visible to keep the same spirit as the original app.

If the issue is that there are too many details displayed, please check #39.

Otherwise, the remaining points are alignment and font size. For alignment, it's a difference I wanted to not make Breezy Weather an exact copy of Geometric Weather. For font size, I won't change it, it was way too small, I think most people went past it without reading it.

Finally, if you want to admire the animated background, please check the live wallpaper feature.

**Comment by papjul** [comment] 2023-06-27 19:53
Closing as #39 is implemented and it is now possible to configure app to have a look closer to Geometric Weather.

**Closed by papjul** 2023-06-27 19:53 UTC
Labels: Feature request
