### ISSUE TITLE
Back button in submenu bring me back to weather screen

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [breezy-weather/breezy-weather#492] opened 2023-09-28 20:19 UTC
### Steps to reproduce

Go into a submenu
Click in the top left corner on the back button
See that u are back on the main screen 

https://github.com/breezy-weather/breezy-weather/assets/73130443/e05d121a-95cc-4177-85b0-2bce1135e668

### Expected behavior

I expect it to take me back to the Settings main menu

### Actual behavior

Takes me back to the main screen

### Weather source used

Open-Meteo

### Breezy Weather version

v4.6.7-beta

### Android version

Android 13

### Device

Google Pixel 5A

### Other details

I didnt know if i had to file a bug report or idea for this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2023-09-28 20:35
Duplicate of #53

**Closed by papjul** 2023-09-28 20:35 UTC
Labels: Bug, Needs review
