### ISSUE TITLE
Alerts from AccuWeather Using A Different Weather Provider

### ISSUE THREAD

**Issue by HonestAbe7** [breezy-weather/breezy-weather#160] opened 2023-07-15 19:43 UTC
### Describe your suggested feature

So if I change from AccuWeather to another weather provider, can I still opt to get alerts from AccuWeather? If not, please make this an option.

### Other details

Example: If I change to OpenWeather will I still get alerts? If not, I would like to get alerts from AccuWeather. Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment] 2023-07-15 19:49
Duplicate of #89

**Closed by papjul** 2023-07-15 19:49 UTC
Labels: Duplicate, Feature request

**Comment by papjul** [comment] 2023-07-15 20:03
OpenWeather alerts are implemented in app btw, so there is probably no reason to use AccuWeather alerts, especially given they have duplicate issues…

See: https://github.com/breezy-weather/breezy-weather/blob/main/docs/PROVIDERS.md

**Comment by HonestAbe7** [comment] 2023-07-15 20:06
Thanks for answering my question. 👍

**Comment by HonestAbe7** [comment] 2023-07-15 20:14
I just tried to change to OpenWeather and the temperature stayed the same. Guess I will keep it at AccuWeather. I tried to even add my location using a different weather provider and it wouldn't let me after changing the weather provider.

**Comment by min7-i** [comment] 2023-07-15 20:55
> I just tried to change to OpenWeather and the temperature stayed the same. Guess I will keep it at AccuWeather. I tried to even add my location using a different weather provider and it wouldn't let me after changing the weather provider.

I suppose this is only a matter of choosing the right settings in the app. This is probably a topic other users might be interested in as well, so would you mind creating a [new discussion](https://github.com/breezy-weather/breezy-weather/discussions/new/choose) for this and describing what you tried already in some more detail?

**Comment by HonestAbe7** [comment] 2023-07-15 21:25
Sure!
