### ISSUE TITLE
hope to adjust the size of the Material You - Current widget to make it look more coordinated with the Google clock widget

### ISSUE THREAD

**Issue by Zhoneym** [breezy-weather/breezy-weather#585] opened 2023-12-04 05:13 UTC
### Describe your idea

I hope to adjust the size of the Material You - Current widget to make it look more coordinated with the Google clock widget，It's better to be slightly larger 
![Screenshot_20231204-125912_Pixel 启动器](https://github.com/breezy-weather/breezy-weather/assets/140673973/c388999f-c4ac-432d-8516-05d2322daf1d)
![Screenshot_20231204-125859_Pixel 启动器](https://github.com/breezy-weather/breezy-weather/assets/140673973/dcc780f7-41b4-43af-9bb1-b84a23fc8eda)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.11 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2023-12-04 05:46
Duplicate of #316?

**Closed as not planned** 2023-12-04 05:48 UTC
Labels: Duplicate, Idea
