### ISSUE TITLE
Crash when using Notification time picker 

### ISSUE THREAD

**Issue by Flouzr** [breezy-weather/breezy-weather#925] opened 2024-04-11 10:59 UTC
### Steps to reproduce

1. Attempt to set the time for daily notifications.
2. Application crashes

### Expected behavior

Application shouldn't crash

### Actual behavior

Application crashes

### Weather source used

Open-Meteo

### Breezy Weather version

5.1.8

### Android version

14

### Device

Pixel 8 Pro

### Other details

Crash log: 
5.1.7 crash -> https://pastebin.com/aPdDsCeY
5.1.8 crash -> https://pastebin.com/z4PMFkYa

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.1.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2024-04-11 11:30
Duplicate of #799

**Closed by papjul** 2024-04-11 11:30 UTC
Labels: Bug, Needs review
