### ISSUE TITLE
Usar un mapa (tipo google, bing, here) para seleccionar la ubicación deseada

### ISSUE THREAD

**Issue by EdgarOns** [breezy-weather/breezy-weather#1330] opened 2024-09-26 08:08 UTC
### Link to publicly available documentation of the API

-

### Available and not available data

It would be ideal to improve the search for locations, without having to rely on a limited database. The best option is to select directly on a map (whether from Google, Bing or another map server) the exact place for which we want to know the weather forecast. In this way, we can know the weather in any corner of the planet.

(Español)
Sería idóneo mejorar la búsqueda de ubicaciones, sin necesidad de depender de una base de datos limitada.  

La mejor opción es seleccionar directamente en un mapa (sea de google, bing u otro servidor de mapas) el lugar exacto para el cual deseamos conocer el pronóstico del tiempo. De esta forma, podremos conocer el tiempo meteorológico en cualquier rincón del planeta.

### Are you going to develop yourself the new source for the app?

No.

### Give a bit more details or context about this source

It would modernize the application even more. It would compete better against the rest of the weather applications. It would offer better service to users.

(Español)
Modernizaría aún más la aplicación. Competiría mejor contra el resto de aplicaciones meteorológicas. Ofrecería un mejor servicio a los usuarios.

### Acknowledgements

- [X] I have searched [the existing sources](https://github.com/breezy-weather/breezy-weather/blob/main/docs/SOURCES.md) and [the existing new source requests](https://github.com/breezy-weather/breezy-weather/issues?q=is%3Aissue+label%3A%22New+source%22+no%3Amilestone+-label%3ADuplicate) and this is a new source, **NOT** a duplicate or related to another open OR closed issue.
- [X] This source has a free-tier available (not a trial period), and if it is a main weather source, it includes free hourly forecast
- [X] This source does not require sensitive information (billing info, phone number, etc) to subscribe to the free-tier
- [X] I understand there may be technical limitations that may prevent implementing this source (for example, the lack of coordinates information)
- [X] I wrote my request in English. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2024-09-26 08:36
Wrong template. Duplicate of #10

**Closed by papjul** 2024-09-26 08:36 UTC
Labels: New source, Needs review
