### ISSUE TITLE
Inaccurate weather data doesn't match source

### ISSUE THREAD

**Issue by benurban** [breezy-weather/breezy-weather#1217] opened 2024-07-22 17:17 UTC
### Steps to reproduce

I pulled up the current weather data for my location (Baltimore, MD, USA).

### Expected behavior

I expected it to say it's raining.
![IMG_20240722_122351405_AE](https://github.com/user-attachments/assets/1e19633e-a862-4b88-9bef-5cfbf3ebae58)

### Actual behavior

![Screenshot_20240722-122429](https://github.com/user-attachments/assets/474da41a-756d-4199-b488-64a000627a33)

### Weather source used

Open Meteo

### Breezy Weather version

5.2.5_freenet

### Android version

Android 14

### Device

Motorola Moto G 5G 2024

### Other details

I went to OpenMeteo's site to see what I could find, and it _did_ report the precipitation. Here's the API URL I used:
https://api.open-meteo.com/v1/forecast?latitude=39.3&longitude=-76.5&current=precipitation,rain,showers,weather_code&hourly=precipitation_probability,precipitation,rain,showers,weather_code&daily=weather_code,precipitation_sum,rain_sum,showers_sum,precipitation_hours,precipitation_probability_max&temperature_unit=fahrenheit&wind_speed_unit=mph&timezone=America%2FNew_York&forecast_days=1
and the results I got:
[forecast.json](https://github.com/user-attachments/files/16337364/forecast.json)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [ ] I have updated the app to **[version 5.2.6 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version. _EDIT_: I tried downloading and installing 5.2.6, and the version number didn't change. I use F-Droid, and the new version isn't there yet.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2024-07-22 18:31
Says it was last refreshed 1 hr ago, so it's the weather from last hour. Btw, Open-Meteo only has forecast, they don't have any actual observation stations, so it will just show the expected forecast for that hour instead. (You probably want to use NWS in the US)

Closing as working as intended?

**Closed** 2024-07-22 18:35 UTC
Labels: Bug, Needs more info
