### ISSUE TITLE
The location list button is duplicated on large screens

### ISSUE THREAD

**Issue by Netocon** [breezy-weather/breezy-weather#682] opened 2024-02-16 22:46 UTC
### Steps to reproduce

Open the app, there will be two buttons for the location list (one hamburger and the other with a pin).

![Screenshot_2024-02-16-19-45-06-264_org breezyweather](https://github.com/breezy-weather/breezy-weather/assets/86788503/f601ab70-c7e9-4000-bc87-1ee4c3dd95cb)

### Expected behavior

Only one button should exist.

### Actual behavior

Both buttons do the same thing.

### Weather source used

AccuWeather

### Breezy Weather version

4.6.14

### Android version

Android 12

### Device

Redmi Pad

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2024-02-16 22:54
I'm not sure this qualifies as a bug, this has been like that for years, and I didn't change anything compared to Geometric Weather, except the choice of icon for the icon on the right.

I don't know how a tablet design should look like, I just see it as a shortcut as no one ever said anything about this in years.

**Comment by papjul** [comment] 2024-02-17 10:13
OK, I just tried and I don't have the same issue as you, I only have the drawer icon. I need to do more tests. Did you do anything particular?

**Comment by Netocon** [comment] 2024-02-17 16:34
No, just opening the app already shows the two buttons.

**Comment by suyashgupta25** [comment] 2024-05-01 18:55
@papjul : What would be a better way to fix this?

I was thinking of keeping the hamburger icon in case of large screens and hiding the location pin since this looks more intuitive from user's perspective.

**Comment by papjul** [comment] 2024-05-03 07:37
@suyashgupta25 Thank you for your interest in this issue!

That's also my view here, but I would like an analysis first. Although I don't have a tablet and didn't work on tablet implementation (previous developer did), I thought it was already there.

I have a theory where there is something similar as what happens in #745 where very large devices have inconsistent behavior. For example, the locations icon is maybe hidden in landscape mode only while the drawer opens starting from a specific width? But I could be wrong. I didn't have a look before because I don't have a particular interest in tablets and the Android emulator slows down my computer too much.

**Comment by suyashgupta25** [comment] 2024-05-03 13:48
@papjul : I can look into this issue. I can start looking into how to hide the drawer by default and later check for portrait and landscape how the view is. Later I will check how to hide the location icon for large screen devices. What do you think?

I also don't have a tablet but I have a high-performance system so I don't have issues with launching large screen emulators.

**Comment by papjul** [comment] 2024-05-03 14:12
IMO, it should be that way on tablets*, but let me know what you think!

| Feature | Orientation | Behavior |
| ------ | ---- | --- |
| Icon | Portrait | Drawer icon on the left, no locations icon on the right |
| Icon | Landscape | Drawer icon on the left, no locations icon on the right |
| Default status when opening app | Portrait | Closed |
| Default status when opening app | Landscape | Opened |

*We have a Kotlin extension isTablet or something like that, that may need to be tweaked, because sometimes the difference between a phone/phablet/tablet may be hard to distinguish, because you can have a tablet with big display size (grandma tablet) which may not give enough space for a drawer on the left, while you can have phablet (very big phones) devices with a very high resolution and enough space on the left.

**Comment by papjul** [comment] 2024-09-06 18:02
@suyashgupta25 Are you still working on this? Make sure to rebase as I fixed #745 in the meantime, so there is only the icon remaining to fix.

**Comment by ecawthorne** [comment] 2024-10-02 16:56
Could this be fixed by changing the resource file to account for both portrait and landscape? E.g changing [`menu-w640dp-land`](https://github.com/breezy-weather/breezy-weather/tree/main/app/src/main/res/menu-w640dp-land) to `menu-w640dp`?

**Comment by min7-i** [comment] 2024-10-12 08:33
> E.g changing menu-w640dp-land to menu-w640dp?

Sounds like a good solution to me. _I can confirm that this works on a Samsung tablet (Android 14) and on a Pixel Fold (emulated with A14)._

**Closed** 2024-10-13 08:50 UTC
Labels: Bug, Open to contributions, Needs review, Priority: low
