### ISSUE TITLE
[NWS] Infrequent errors when fetching data

### ISSUE THREAD

**Issue by gbakeman** [breezy-weather/breezy-weather#833] opened 2024-03-21 14:45 UTC
### Steps to reproduce

1. Wait indeterminate amount of time
2. BW reports an error occurred fetching weather

### Expected behavior

Weather update occurs without issue

### Actual behavior

Unknown error is encountered

### Weather source used

National Weather Service

### Breezy Weather version

5.1.7 (normal repo version)

### Android version

Android 9

### Device

OnePlus 6T

### Other details

@papjul Thanks for fielding my questions in #421. The error presented to me initially is:

> Errors during refresh

> ! National Weather Service (NWS): Weather data refresh failed
> \- Current location

I'll attach two instances of debug logs that I captured. They aren't necessarily all from version 5.1.7 but I do know that the same error is still occurring. I haven't been able to extract anything useful, so hopefully you can. In the last issue, I was hoping to see some changes with the way in which errors are collected in Breezy Weather. If you could automatically capture the debug log around when an error occurs then archive it into user storage that would be super useful for reporting bugs.

Thank you!

[bwerror1.txt](https://github.com/breezy-weather/breezy-weather/files/14696808/bwerror1.txt)
[bwerror2.txt](https://github.com/breezy-weather/breezy-weather/files/14696809/bwerror2.txt)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.1.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2024-03-21 15:06
It's curious that the error log shows nothing. Can you refresh manually in the app and export the crash log right after?

When I implemented NWS, I came accross one issue for one state in particular where the data was not correctly published by the office/not yet available and I needed to wait a few minutes before data was available from the server. I believe this is the same issue, but I would like a log to confirm.

**Comment by gbakeman** [comment] 2024-03-21 15:12
> When I implemented NWS, I came accross one issue for one state in particular where the data was not correctly published by the office/not yet available and I needed to wait a few minutes before data was available from the server.

That's interesting, I wouldn't be surprised if it was mine! Can't believe you have to support edge cases of US states let alone different weather sources.

Here's a crash/debug log I captured just after doing a refresh. The refresh was fine by its self (difficult problem to manually reproduce), but I hope this helpful nonetheless. Thank you again for your response.

[bw-goodrefresh.txt](https://github.com/breezy-weather/breezy-weather/files/14697199/bw-goodrefresh.txt)

**Comment by papjul** [comment] 2024-03-21 15:24
I had the issue with the office of Raleigh.

The error log is only useful when the error happens.

The API of NWS is unique for all states, however each state is responsible to publish their own data (some offices have more or less data) using a grid of 2,5 km x 2,5 km. We send your longitude and latitude to NWS and they give us the matching office and grid for this location. Sometimes we get an error 5xx which means the server is unable to process our request, most likely there is an issue with the data/it's not yet published, as it is usually fixed within a few minutes. As I don't live in the US/don't use any location in the US, I don't encounter the issue myself, but I would have thought this kind of error to be the exception.

**Comment by gbakeman** [comment] 2024-03-21 15:28
Ah ok, yeah that's probably not my office. Very interesting description of how that all works. So because there is no explicit error being recorded by Breezy Weather when the error occurs, does that mean something else is going on? Wouldn't it still catch and record a server error like you specified?

**Comment by papjul** [comment] 2024-03-21 16:27
> So because there is no explicit error being recorded by Breezy Weather when the error occurs, does that mean something else is going on? Wouldn't it still catch and record a server error like you specified?

Usually, this means that the data result from the API is empty.

You can see here that we throw an error in that case:
https://github.com/breezy-weather/breezy-weather/blob/v5.1.7/app/src/src_nofdroid/org/breezyweather/sources/nws/NwsResultConverter.kt#L67-L70

And when you look at how we handle different exception types, you will see that we only print technical details for specific types. `WeatherException` is not one of them, since there is nothing to debug, the data is just empty.
https://github.com/breezy-weather/breezy-weather/blob/v5.1.7/app/src/main/java/org/breezyweather/sources/RefreshHelper.kt#L610-L643

**Comment by gbakeman** [comment] 2024-03-21 16:48
Ok, I think that makes sense. It sounds more like the source I'm using (NWS) isn't that good from a communication/API standpoint and I should maybe look for other sources if I want more consistent updates. If that all makes sense and you don't see anything else to do with this issue, please feel free to close as you see fit. Thanks again for your help!

**Comment by papjul** [comment] 2024-03-21 17:13
I will add in the next version an "Invalid or incomplete data received from server" in the case I mentioned to make it easier to troubleshoot, if you're still willing to give it another shot. If not, I will still keep the issue open as I'm pretty sure others people are affected.

**Comment by gbakeman** [comment] 2024-04-02 20:13
Here's the output from an automatic refresh error:

```
Errors during refresh


! National Weather Service (NWS): Weather data refresh failed
  - Current location
```

I wasn't able to get a debug log around the same time, but I did catch the refresh error during a manual refresh. [Here](https://github.com/breezy-weather/breezy-weather/files/14843200/breezyweather-manualrefresh-debug.txt) is that one.

Thank you for getting back to me on this!

**Comment by papjul** [comment] 2024-04-02 20:18
Hmm, so it's not what I thought. And there is nothing in the debug logs, which doesn't help.
Can you give me your state/the biggest city nearby, so I can try to reproduce the issue on my side?
You can send it to me privately on the Matrix server if you prefer: https://matrix.to/#/#breezy-weather-space:matrix.org

**Closed** 2024-04-11 16:33 UTC
Labels: Bug

**Comment by gbakeman** [comment] 2024-04-11 16:57
Thanks for your work on this!

**Comment by papjul** [comment] 2024-04-11 16:58
I didn't do much, I just added a more explicit error, so you know there's nothing wrong on Breezy Weather side ;)

**Comment by gbakeman** [comment] 2024-04-11 17:00
All the same, I appreciate your effort going back and forth with me here and on the Matrix chatroom. You've been doing a fantastic job keeping this app going!
