### ISSUE TITLE
Live wallpaper only show sunny condition (version 5.1.6_gplay and after))

### ISSUE THREAD

**Issue by AndyZHENG0715** [breezy-weather/breezy-weather#854] opened 2024-03-28 14:54 UTC
### Steps to reproduce

1. Turn on application
2. Open setting 
3. Go to live wallpaper 
4. Select weather condition manually 

### Expected behavior

Preview of live wallpaper of different weather condition should be shown 

### Actual behavior

Only sunny weather condition will be shown

### Weather source used

AccuWeather

### Breezy Weather version

5.1.6_gplay and after

### Android version

Xiaomi HyperOS 1.0.4.0.UMBMIXM (Based on Android 14)

### Device

Xiaomi 13 Pro

### Other details

Version 5.1.5 and before behave normally

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.1.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2024-03-28 14:58
Duplicate of #831

**Closed by papjul** 2024-03-28 14:58 UTC
Labels: Bug, Needs review
