### ISSUE TITLE
Material You widget improvements

### ISSUE THREAD

**Issue by M00NJ** [breezy-weather/breezy-weather#536] opened 2023-10-18 18:45 UTC
### Describe your idea

I compared the Material You widget to the one by Google and noticed some things that could be improved.

Breezy (Left) / Google (Right):

![Image1](https://github.com/breezy-weather/breezy-weather/assets/82398591/ddd58ad3-cb91-4466-8464-eeca38de0e6d)

1. Change font color to `primary`  
    (it's `onsecondary` now)
2. Align text to `center` 
    (it's aligned to the `right` now)
3. Use `regular` font
    (it's `bold` now)
4. Change font size based on string length
5. Make widget resizable

Making sure the temperature text is aligned properly might require some logic to always place it inside the green circle and possibly reduce the font size, if the string is longer because Fahrenheit or Kelvin is being used. I created some mock-ups to show what I mean:

![Image2](https://github.com/breezy-weather/breezy-weather/assets/82398591/c49c79b3-5ed7-4a1c-8638-d885098ec6f7)

Mock-up without the circles:

![Image3](https://github.com/breezy-weather/breezy-weather/assets/82398591/4bd5b022-3012-49e9-81a4-30ac79ce335c)

The google widget is also resizable:

![Image4](https://github.com/breezy-weather/breezy-weather/assets/82398591/d3d43943-bd3d-4a7c-8c96-a5b10583db59)

Unfortunately I don't now HTML / Widgets or I would take this on myself. But I hope the mock-ups and suggestions are somewhat useful... :)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.9 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2023-10-18 20:11
Duplicate of #316. Feel free to complete the existing issue if some cases are missing.

**Closed by papjul** 2023-10-18 20:11 UTC
Labels: Idea, Needs review, Widgets

**Comment by M00NJ** [comment] 2023-10-20 23:19
Sorry for the duplicate. I don't know why I missed it when I was going trough them...
