### ISSUE TITLE
Mold value seems abnormally high

### ISSUE THREAD

**Issue by trlef19** [breezy-weather/breezy-weather#1264] opened 2024-08-19 07:47 UTC
### Steps to reproduce

Check out mold value

### Expected behavior

Have a normal value

### Actual behavior

Has a really big number as a value. Seems wrong

### Weather source used

AccuWeather

### Breezy Weather version

5.2.7

### Android version

Android 14

### Device

Galaxy s24+

### Other details

![Screenshot_20240819_104102_Breezy Weather](https://github.com/user-attachments/assets/16c55768-c9de-44f6-b0af-68927431b5f2)
It says Mold and μ³=m³

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment] 2024-08-19 08:00
Duplicate of #884

**Closed by papjul** 2024-08-19 08:00 UTC
Labels: Bug, Needs review
