### ISSUE TITLE
Make refresh automaticaly by opening app

### ISSUE THREAD

**Issue by Yabadabadooooo** [breezy-weather/breezy-weather#379] opened 2023-08-16 22:34 UTC
### Describe your idea

When you open the app and the last refresh is longer than Xh then automaticaly refresh

THX for the awesomeness you guys do for us ❤️

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to an existing feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.5.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment] 2023-08-16 22:41
Duplicate of #248, everything said there is still valid

**Closed by papjul** 2023-08-16 22:41 UTC
Labels: Idea
